# 'racket' build environment

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y sudo
RUN apt-get update && apt-get install -y racket
RUN apt-get update && apt-get install -y emacs-nox
RUN apt-get update && apt-get install -y openssl

