FROM ubuntu:16.04

# This is intended to be an environment with general utilities
# installed in it, usable for most non-specialised purposes.

RUN echo benubuntu dockerfile

RUN apt-get update && apt-get install -y sudo

RUN apt-get update && apt-get install -y vim

RUN apt-get update && apt-get install -y emacs

