# 'go' build environment

FROM debian:stretch

RUN apt-get update && apt-get install -y sudo curl

RUN apt-get update && apt-get install -y youtube-dl

RUN apt-get update && apt-get install -y sox libsox-fmt-all

