# debian stretch general work environment

FROM debian:stretch

RUN apt-get update && apt-get install -y sudo

RUN apt-get update && apt-get install -y youtube-dl sox libsox-fmt-all irssi alpine curl

RUN apt-get update && apt-get install -y direwolf

RUN apt-get update && apt-get install -y gqrx-sdr
