# debian stretch general work environment

FROM debian:stretch

RUN apt-get update && apt-get install -y sudo

RUN apt-get update && apt-get install -y youtube-dl sox libsox-fmt-all irssi alpine curl

RUN apt-get update && apt-get install -y direwolf

RUN apt-get update && apt-get install -y gqrx-sdr

RUN apt-get update && apt-get install -y less vim

RUN apt-get update && apt-get install -y less gthumb

RUN apt-get update && apt-get install -y less libreoffice

RUN apt-get update && apt-get install -y texlive-latex-base xpdf

RUN apt-get update && apt-get install -y dnsutils

RUN apt-get update && apt-get install -y whois

RUN apt-get update && apt-get install -y texlive-latex-recommended texlive-latex-extra

RUN apt-get update && apt-get install -y git

RUN apt-get update && apt-get install -y less zip
